parameters:
#    dummy_blog.example.class: Dummy\BlogBundle\Example

services:
#    dummy_blog.example:
#        class: %dummy_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
